[workspace]
resolver = "3"
members = ["api", "client", "server", "service", "stresstest"]
default-members = ["server"]

[profile.release]
# In release, however, we do want full debug information to report
# panic and error stack traces to Sentry.
debug = "line-tables-only"
lto = "thin"
