[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
proto-codegen = { path = "../proto-codegen" }
rusqlite = "0.36.0"
uuid = { version = "1.17.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.20.0"
