[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
elegant-departure = { version = "0.3.1", features = ["tokio"] }
proto-codegen = { path = "../proto-codegen" }
service = { path = "../service" }
tokio = { version = "1.45.1", features = ["full"] }
tonic = { version = "0.13.1" }
