name: CI

on:
  push:
    branches:
      - master

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup component add clippy rustfmt rust-docs --toolchain stable

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ github.job }}

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings

      - name: Docs
        run: cargo doc --workspace --all-features --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -Dwarnings

  test_all:
    name: Test (all features)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: |
          rustup toolchain install stable --profile minimal --no-self-update

      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ github.job }}

      - name: Run Tests
        run: cargo test --workspace --all-features
